wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1655478936
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 80
      3:
      - 1
      - 17
      4: 3.9.13
      5: 0.12.18
      8:
      - 5
